repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1  # Use the latest version
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_fmt
      - id: terraform_validate
      