name: Dev - TF Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true
        type: string

env:
  TF_VERSION: "1.13.3"
  TF_DIR: "./dev"
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
    # - name: Validate Confirmation
    #   run: |
    #     if [ "${{ github.event.inputs.confirmation }}" != "destroy" ]; then
    #       echo "ERROR: Confirmation input must be 'destroy' to proceed"
    #       echo "You entered: ${{ github.event.inputs.confirmation }}"
    #       exit 1
    #     fi
    #     echo "Confirmation validated. Proceeding with destroy..."

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: |
        echo "Planning infrastructure destruction..."
        terraform plan -destroy -no-color -out=destroy-plan

    - name: Terraform Destroy
      run: |
        echo "Destroying infrastructure..."
        terraform apply --auto-approve destroy-plan
        echo "Infrastructure destroyed successfully"
